### ISSUE TITLE
file-storage.tar.gz

### ISSUE THREAD

**Issue by drbyte** [LaravelDaily/Laravel-File-Storage#1]
Did you mean to include the `file-storage.tar.gz` file in this repo? 
It appears to be a prior version of what this repo was built from.

**Comment by PovilasKorop** [comment]
@drbyte great point, thank you, deleted the file: https://github.com/LaravelDaily/Laravel-File-Storage/commit/621e26756062e1afd703e0fd1e741300bb2b4a99
