### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by josegus** [LaravelDaily/Laravel-File-Storage#2]
Using the demo and user and pass: admin@admin.com - password is not working

**Comment by PovilasKorop** [comment]
@josegus fixed it, thanks

**Comment by ajbm6** [comment]
Still cant login with the given credentials

**Comment by PovilasKorop** [comment]
@ajbm6 re-seeded database again. Pretty weird that someone changes the password, will get into that deeper if I have more free time.
