### ISSUE TITLE
Folder and Files View

### ISSUE THREAD

**Issue by shinnovate** [LaravelDaily/Laravel-File-Storage#6]
Hi Sir,

I do have questions. How can I display the files & folders created by admin can be a view for other users too? Instead of users create their own. I have enabled the edit, create, delete just for admin. The second question is, how can I change the filter button by using the dropdown list? The dropdown list just has a file name only. Thank you. Sorry, I'm still a beginner in laravel. I just try to play with this clone to learn.

**Comment by PovilasKorop** [comment]
@shinnovate sorry these are not simple questions, we don't provide instructions on how to customize our Laravel code.
